const products = [
    {
       id: 'mercadopago',
       name: 'MERCADO PAGO',
       descripcion: 'Working with Mercado Pago Integrations Products to understand pain points and enhance user experiences.I was DX Owner for MP Integrations. DX (Developer eXperience) focus on devs as a type of user. I led initiatives to make sure products like Checkouts have everything devs needed. I.e. good documentation, useful SDKs and APIs that follow good practices.',
       tag1: '.UX Research',
       tag2: '.Product Management',
       tag3: '.Developer Experience',
       seeMore: 'https://www.mercadopago.com.ar/developers/es',
       image1: '/img/first-img.png',
       image2: '/img/final1.png',
       image3: '/img/final2.png',
       image4: '/img/Untitled.png',
       image5: '/img/credenciales.png',
       cta: 'See live',
    },
    {
       id: 'chicprogramando',
       name: 'CHICAS PROGRAMANDO',
       descripcion: 'I was part of the core team of Chicas Programando, a non profit that aimed to encourage women and girls into STEM careers. I was part of the design and developing process for the webApp. For example, I was in charge of the frontend development of the Home page. I also organized events and created different types of communications: flyers, social media posts, etc.',
       tag1: '.Frontend Coding',
       tag2: '.Product Management',
       tag3: '.Design',
       seeMore: 'https://github.com/chicasprogramandoarg', 
       image1: '/img/HOME.png',
       image2: '/img/view.png',
       image3: '/img/pins.png',
       image4: '/img/slice3.png',
       image5: '/img/buttons.png',
       cta: 'See repo',
    },
    {
        id: 'aromas',
        name: 'AROMAS',
        descripcion: 'The final project I presented at my Backend specialization diploma at Universidad Tecnológica Nacional in Argentina.his is an online bakery where you can shop online, book a custom request for special events and send a form for specific questions that will send a confirmation to your email with the data you provided. Coded with HTML, CSS, PHP and MySQL.',
        tag1: '.Design',
        tag2: '.Frontend Coding',
        tag3: '.Backend Coding',
        seeMore: 'https://utn-examen1.000webhostapp.com/',
        image1: '/img/aromas1.png',
        image2: '/img/aromas2.png',
        image3: '/img/aromas3.png',
        image4: '/img/aromas4.png',
        image5: '/img/aromas5.png',
        cta: 'See live',
    },
    {
        id: 'thisdot',
        name: 'THIS DOT',
        descripcion: 'As a Product consultant, I managed communications, built tech communities and provided marketing services to IT clients.  My job was to understand the dev journey for products where users are developers. I owned initiatives to confirm projects added value to users. I led actions such as usability tests, meetups, documentation creations, Open Source maintenance, etc. A few clients: Google, Paypal, Node.js.',
        tag1: '.Design',
        tag2: '.Marketing',
        tag3: '.Developer Experience',
        seeMore: 'https://github.com/SofiEstevez/admin',
        image1: '/img/thisdot1.png',
        image2: '/img/thisdot2.png',
        image3: '/img/thisdot3.png',
        image4: '/img/report.png',
        image5: '/img/thisdot5.png',
       
        cta: 'See repo',
    },
    {
        id: 'cmservices',
        name: 'CM SERVICES',
        descripcion:'A selection of freelance work.I provided marketing, design and community management services. I designed strategies to create cohesive identities and make sure brands reach their intended target. My tasks included creating social media calendars, posting content and programmng ads in Facebook, Instagram and Twitter.  I also delivered reports to analyze results and adjust efforts.',
        tag1: '.Design',
        tag2: '.Marketing',
        tag3: '.Community Management',
        seeMore:'https://drive.google.com/drive/folders/1TMxD_sehESFMpYqqJhHZvA1ep5k6G3Ai?usp=share_link',
        image1: '/img/thisdot1.png',
        image2: '/img/thisdot2.png',
        image3: '/img/thisdot3.png',
        image4: '/img/report.png',
        image5: '/img/thisdot5.png',
        cta: 'See more',
    }
   ]
   export default products;